name: Atualizar README

on:
  schedule:
    # Executa todo dia às 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch: # Permite rodar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checar repositório
        uses: actions/checkout@v3

      - name: Atualizar README
        run: |
          TIMESTAMP=$(date '+%d/%m/%Y %H:%M:%S')
          cat <<EOT > README.md
# 👋 Olá, eu sou Gabriel Oliveira

Sou Analista de Desenvolvimento de Sistemas e Analista de TI, apaixonado por tecnologia e por criar soluções práticas para o dia a dia.

💻 Trabalho com suporte técnico, manutenção de computadores, configuração de sistemas e gestão de sistemas acadêmicos. Gosto de resolver problemas e otimizar processos, sempre aprendendo novas ferramentas e técnicas.

---

## 🛠 Habilidades Técnicas

- 💻 Suporte técnico e manutenção de computadores  
- 🖥 Configuração de sistemas e softwares  
- 🌐 Redes e infraestrutura básica  
- 🔐 Cibersegurança básica  
- 🐧 Linux e Windows Server  
- 🖱 Gestão de sistemas acadêmicos  
- ⚡ Resolução de problemas e troubleshooting  

---

## 🚀 Interesses

- Aprender novas tecnologias e linguagens de programação  
- Explorar soluções em cibersegurança e redes  
- Automatização de processos e otimização de sistemas  
- Criar projetos inovadores e práticos no dia a dia de TI  

---

## 📂 Experiência Profissional

- **Associação Universitária Santa Úrsula** – Analista de Desenvolvimento de Sistemas / Analista de TI (04/2023 – atualmente)  
  Gestão de sistemas acadêmicos, suporte a usuários, manutenção e configuração de equipamentos e softwares.

- **Distribuidora de Bebidas Amaral** – Assistente de Suporte de TI (01/2020 – 04/2022)  
  Suporte técnico, manutenção de computadores, atendimento ao usuário e configuração de softwares corporativos.

---

## 📫 Contato

- E-mail: [gabrieloliveira79@gmail.com](mailto:gabrieloliveira79@gmail.com)  
- GitHub: [SeuLinkAqui](#)  

---

> Última atualização: $TIMESTAMP
EOT

      - name: Commit e push
        run: |
          git config --global user.name "Gabriel Oliveira"
          git config --global user.email "gabrieloliveira79@gmail.com"
          git add README.md
          git commit -m "Atualização automática do README [GitHub Actions]" || echo "Nenhuma mudança para commitar"
          git push
