name: Diagnosticar Nome de Arquivo

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Listar arquivos no diretório
        run: ls -la
