name: Atualizar README Dinâmico

on:
  schedule:
    # Atualiza a cada hora
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Atualizar Perfil

    steps:
      - uses: actions/checkout@v3

      # Atualiza data e hora
      - name: Atualizar data e hora
        uses: Srunky/github-readme-time@main
        with:
          REPLACE_ID: "time"
          TIME_ZONE: "America/Sao_Paulo"
          TIME_FORMAT: "DD/MM/YYYY, HH:mm:ss (GMT-3)"

      # Atualiza log de atividade recente
      - name: Atualizar atividade recente
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'chore: atualiza log de atividade recente'
          MAX_LINES: 7
          REPLACE_MARKER: "{#recent_activity#}"
