name: Atualizar README Dinâmico

on:
  schedule:
    # Atualiza a cada hora
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Atualizar Perfil

    steps:
      - uses: actions/checkout@v3

      # Etapa 1: Atualiza a data e hora usando um comando direto e seguro
      - name: Atualizar data e hora
        run: |
          DATE=$(TZ="America/Sao_Paulo" date +'%d/%m/%Y, %H:%M:%S (GMT-3)')
          sed -i "s||$DATE|" README.md
      
      # Etapa 2: Atualiza o log de atividade e faz o commit de TODAS as alterações
      - name: Atualizar atividade e fazer commit
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'chore: atualiza log de atividade e timestamp'
          MAX_LINES: 7
          REPLACE_MARKER: "{#recent_activity#}"
